services:
  frontend:
    image: frontend
    build:
      context: frontend
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3000:4200
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "./node_modules/@angular/cli/bin/ng", "serve", "--host", "0.0.0.0"]
